version: '3'

volumes:
  kittygram_pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - kittygram_pg_data:/var/lib/postgresql/data
  backend:
    image: nastyapan98/backend_f
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    env_file: .env
    image: nastyapan98/frontend_f
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: nastyapan98/gateway_f
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static/
      - media:/app/media